## NumPy Practice Guide

### Imports & version
    Basics → Intermediate

### Imports & version

In [1]:
import numpy as np
import time
import timeit

print("NumPy version:", np.__version__)

NumPy version: 1.26.4


### Array creation

In [2]:
# 1D creation
a = np.arange(10)
print("arange(10):", a)

arange(10): [0 1 2 3 4 5 6 7 8 9]


In [3]:
# linspace
b = np.linspace(0, 20, num=5)
print("linspace(0,20,5):", b)

linspace(0,20,5): [ 0.  5. 10. 15. 20.]


In [4]:
# Zeros
z = np.zeros((3,4))
print("zeros:\n", z)

zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
o = np.ones(5)
print("ones:", o)

ones: [1. 1. 1. 1. 1.]


In [6]:
# Full
f = np.full((2,3), 7)
print("full:\n", f)

full:
 [[7 7 7]
 [7 7 7]]


In [7]:
e = np.empty((2,3))  # values not initialised
print("empty (uninitialised):\n", e)

empty (uninitialised):
 [[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# reshape
c = np.arange(12).reshape(3,4)
print("reshape 3x4:\n", c)

reshape 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Identity & diagonal

In [9]:
I = np.eye(4)
print("Identity 4x4:\n", I)

Identity 4x4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
D = np.diag([10,20,30,40])
print("Diagonal:\n", D)

Diagonal:
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


### Indexing & slicing (1D & 2D)

In [11]:
arr = np.arange(20).reshape(4,5)
print("arr:\n", arr)

arr:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [12]:
# row 1
print("arr[1]:", arr[1])

arr[1]: [5 6 7 8 9]


In [13]:
# column 2
print("arr[:,2]:", arr[:,2])

arr[:,2]: [ 2  7 12 17]


In [14]:
# submatrix
print("arr[1:3, 2:5]:\n", arr[1:3, 2:5])

arr[1:3, 2:5]:
 [[ 7  8  9]
 [12 13 14]]


In [15]:
# fancy indexing (pick rows 0 and 2)
print("rows 0 and 2:\n", arr[[0,2], :])

rows 0 and 2:
 [[ 0  1  2  3  4]
 [10 11 12 13 14]]


In [16]:
# boolean masking (even numbers)
mask = (arr % 2 == 0)
print("even elements (flattened):", arr[mask])

even elements (flattened): [ 0  2  4  6  8 10 12 14 16 18]


In [17]:
# assignment with mask
arr2 = arr.copy()
arr2[arr2 % 3 == 0] = -1
print("arr2 (multiples of 3 replaced with -1):\n", arr2)

arr2 (multiples of 3 replaced with -1):
 [[-1  1  2 -1  4]
 [ 5 -1  7  8 -1]
 [10 11 -1 13 14]
 [-1 16 17 -1 19]]


### Fancy indexing examples

In [18]:
# example: select elements by index arrays
m = np.arange(16).reshape(4,4)
rows = np.array([0,1,2])
cols = np.array([3,2,1])
print("m:\n", m)
print("\npick (0,3),(1,2),(2,1):", m[rows, cols])


m:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

pick (0,3),(1,2),(2,1): [3 6 9]


### Broadcasting

In [19]:
A = np.arange(3).reshape(3,1)    # shape (3,1)
B = np.array([0,10,20])          # shape (3,)
print("A:\n", A)
print("\nB:", B)
print("\nA + B  => broadcasted result:\n", A + B)  # (3,3)

# scalar broadcasting
M = np.ones((2,3))
print("\nM + 5:\n", M + 5)


A:
 [[0]
 [1]
 [2]]

B: [ 0 10 20]

A + B  => broadcasted result:
 [[ 0 10 20]
 [ 1 11 21]
 [ 2 12 22]]

M + 5:
 [[6. 6. 6.]
 [6. 6. 6.]]


### Aggregations & axis ops

In [20]:
rng = np.random.default_rng(0)
M = rng.integers(1, 10, size=(4,5))
print("M:\n", M)

print("\nsum all:", M.sum())
print("\nsum axis=0 (columns):", M.sum(axis=0))
print("\nsum axis=1 (rows):", M.sum(axis=1))
print("\nmean axis=1:", M.mean(axis=1))
print("\nargmax axis=1 (index of max in each row):", M.argmax(axis=1))
print("\ncumsum axis=0:\n", M.cumsum(axis=0))


M:
 [[8 6 5 3 3]
 [1 1 1 2 8]
 [6 9 5 6 9]
 [7 6 5 6 9]]

sum all: 106

sum axis=0 (columns): [22 22 16 17 29]

sum axis=1 (rows): [25 13 35 33]

mean axis=1: [5.  2.6 7.  6.6]

argmax axis=1 (index of max in each row): [0 4 1 4]

cumsum axis=0:
 [[ 8  6  5  3  3]
 [ 9  7  6  5 11]
 [15 16 11 11 20]
 [22 22 16 17 29]]


### Sorting & searching

In [21]:
vals = np.array([3,1,8,2,7,4])
print("sorted:", np.sort(vals))
print("argsort:", np.argsort(vals))  # positions that would sort array

# where
print("positions > 4:", np.where(vals > 4))

# unique + counts
uniq, counts = np.unique(np.array([1,2,2,3,1,4,2]), return_counts=True)
print("unique:", uniq)
print("counts:", counts)


sorted: [1 2 3 4 7 8]
argsort: [1 3 0 5 4 2]
positions > 4: (array([2, 4], dtype=int64),)
unique: [1 2 3 4]
counts: [2 3 1 1]


### Random numbers

In [22]:
np.random.seed(0)
ri = np.random.randint(0, 10, size=8)
ch = np.random.choice([10,20,30,40], size=5, replace=True)
perm = np.random.permutation(10)

print("randint:", ri)
print("choice:", ch)
print("permutation:", perm)


randint: [5 0 3 3 7 9 3 5]
choice: [30 10 40 30 10]
permutation: [5 2 3 4 9 0 7 6 1 8]


### ravel vs flatten

In [23]:
X = np.arange(12).reshape(3,4)
r = X.ravel()   # view, not copy
f = X.flatten() # copy
r[0] = 999
print("after changing ravel, X[0,0]:", X[0,0])  # changed
f[0] = -1
print("after changing flatten, X[0,0]:", X[0,0]) # unaffected

after changing ravel, X[0,0]: 999
after changing flatten, X[0,0]: 999


### Vectorization vs Python loop (speed test)

In [24]:
# small demo. Increase n to test on your machine.
n = 200_000

# python loop
def py_square(n):
    out = []
    for i in range(n):
        out.append(i*i)
    return out

t0 = time.time()
_ = py_square(n)
t1 = time.time()
print("python loop time:", round(t1-t0,4), "sec")

# numpy vectorized
t0 = time.time()
_ = (np.arange(n) ** 2)
t1 = time.time()
print("numpy vectorized time:", round(t1-t0,4), "sec")


python loop time: 0.0576 sec
numpy vectorized time: 0.007 sec
